tosca_definitions_version: cloudify_dsl_1_3

imports:
  - https://cloudify.co/spec/cloudify/6.3.2/types.yaml
  - plugin:cloudify-ansible-plugin
  - plugin:cloudify-utilities-plugin
  - plugin:cloudify-terraform-plugin

inputs:
  ansible_deployment_id:
    default:
dsl_definitions:
  sources: &sources
    vms:
      hosts:
        master:
          ansible_host: localhost
          ansible_connection: local

node_templates:

  test:
    type: cloudify.nodes.ansible.Executor
    properties:
      ansible_external_venv: { get_capability: [ { get_input: ansible_deployment_id }, ansible_venv, venv] }
      playbook_path: ansible/example.yaml
      sources: *sources
